apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: app
        image: huytm1996/app4:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-dev-service
spec:
  selector:
    app: app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012
