apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: app4
        image: huytm1996/app4:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-uat-service
spec:
  selector:
    app: app4
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30013
